version: 0.2
phases:
  pre_build:
    commands:
      - echo "Prebuild section"
  build:
    commands:
      - echo "Build phase"
      - mvn clean prepare-package war:exploded
  post_build:
    commands:
      - echo "Post build"
      - mkdir -p target/deploy
      - mv target/demo-0.0.1-SNAPSHOT target/deploy/
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*
